상품조회 페이지 데이터 처리 및 상품생성 시 이미지파일 처리
TheSynergyTEAM/cucumberclient pull request #31
Opened 2021-05-10 12:49 UTC by dohye1

- 상품조회시 데이터를 받아와 view에 반영하고, 이미지의 유무에따라 view를 다르게 구성합니다.
- 상품생성시 이미지를 서버에 잘못보내고있어서 그 부분도 같이 수정했습니다.

2021-05-21 01:00 UTC, n2ptune requested changes

2021-05-21 01:00 UTC, n2ptune commented on src/components/detail/DetailInfo/index.tsx
> +            </p>
채팅이 지금 채팅중인 수라는 거겠죠? `views`가 그런 키였나요 조회 수라고 알고있었는데

2021-05-21 01:00 UTC, n2ptune commented on src/components/detail/DetailInfo/index.tsx
> +            </Link>
아이템 상세는 기본적으로 로그인이 필요한거겠죠?

2021-05-21 01:00 UTC, n2ptune commented on src/types/article.d.ts
> +    thumbnailid?: number
썸네일 아이디가 없을 수도 있나요? 노션에는 옵셔널한 표시가 없던데, 만약 옵셔널한 키를 가질 수 있으면 해당 부분도 백엔드분들께 표시해달라고 요청해야 할 것 같아요

2021-05-21 01:00 UTC, n2ptune commented on src/styles/index.ts
> +    overflow-y:auto;
위에 똑같은 속성이 있네요.

2021-05-21 01:27 UTC, dohye1 commented on src/components/detail/DetailInfo/index.tsx
> +            </p>
헐 맞네요 수정할게욥

2021-05-21 01:28 UTC, dohye1 commented on src/components/detail/DetailInfo/index.tsx
> +            </Link>
아 그렇겠네요! 이것도 수정할게용

2021-05-21 01:36 UTC, dohye1 commented on src/types/article.d.ts
> +    thumbnailid?: number
상품 디테일 정보를 얻어올때는 썸네일 아이디를 받아오지 않아서 저렇게만들었는데, 썸네일 아이디포함하지않는 타입(ArticleData)을 만들고, 
```
interface 타입명 extends ArticleData{
    thumbnailid : number;
}
```

이런식으로 수정해도 괜찮을것같은데, 혹시 다른 의견이 있으시다면 알려주십숑!

2021-05-21 01:58 UTC, n2ptune commented on src/types/article.d.ts
> +    thumbnailid?: number
디테일로 받아올 땐 다른가보군요 말씀하신 방법이 괜찮은 것 같아요.

2021-05-23 08:08 UTC, dohye1 commented
타입 수정으로인해서 여러파일을 수정하긴했는데, 내용이 간단해서 커밋단위로 보시면 보기 편하실겁니당

2021-05-23 09:43 UTC, merged